name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: platformio run -d PlatformIO -e esp32dev
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: PlatformIO/.pio/build/esp32dev/firmware.bin
